apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: j3ksz7zkt-nodejs
  janus-idp.io/tekton: j3ksz7zkt-nodejs
  backstage.io/kubernetes-id: j3ksz7zkt-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: j3ksz7zkt-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
